app = "mangansage-api"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  SERVER_NAME = ":8080"
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_URL = "https://mangansage-api.fly.dev"
  DB_CONNECTION = "pgsql"
  DB_PORT = "5432"
  DB_SSLMODE = "require"
  BROADCAST_CONNECTION = "reverb"
  REVERB_HOST = "mangansage-reverb.fly.dev"
  REVERB_PORT = "443"
  REVERB_SCHEME = "https"
  QUEUE_CONNECTION = "sync"
  CACHE_STORE = "file"
  SESSION_DRIVER = "file"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
