APP_NAME: ManganSage
APP_ENV: production
APP_KEY: base64:Q4D9XM++JdDL7dBXfkaoVCSM8WarGuB+Bmop5Q5lFME=
APP_DEBUG: "false"
APP_URL: https://mangansage-api-722613562569.asia-southeast1.run.app

LOG_CHANNEL: stderr
LOG_LEVEL: error

DB_CONNECTION: pgsql
DB_URL: "postgresql://neondb_owner:npg_EbrGC4qXyka9@ep-raspy-bread-ao71oaox.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

SESSION_DRIVER: database
SESSION_LIFETIME: "120"

MAIL_MAILER: smtp
MAIL_HOST: smtp.gmail.com
MAIL_PORT: "587"
MAIL_USERNAME: "familygroupMANGAN@gmail.com"
MAIL_PASSWORD: "shwdvwomljwmtzfx"
MAIL_ENCRYPTION: tls
MAIL_FROM_ADDRESS: "familygroupMANGAN@gmail.com"
MAIL_FROM_NAME: MANGAN

FIREBASE_CREDENTIALS: storage/firebase-credentials.json
